server:
  port: 80

eureka:
  client:
    fetch-registry: true  # 检测服务信息
    # 作为服务进行注册
    register-with-eureka: true
    service-url:
#      defaultZone: http://localhost:7001/eureka # 单机模式
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群模式
spring:
  application:
    name: consumer-order-service
## 超时时间设置
ribbon:
  # 连接后读取数据时间
  ReadTimeout:  3000
  # 创建连接超时时间
  ConnectTimeout: 1000
## feign 日志输出
logging:
  level:
    com.study.cloud.remote.service.FeignPaymentService: debug
